language: node_js

node_js:
  - 12.13.1

cache: yarn

install:
  - yarn install
  - yarn tsc

script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

deploy:
  provider: npm
  email: ponciusz@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
