version: 2
jobs:
  one:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - two:
          requires:
            - one
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
